name: branch and pr validation
on: [push, pull_request]
jobs:
  generate:
    runs-on: ubuntu-latest
    name: validate generation
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go generate ./...
      - run: git diff-index HEAD
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go test ./...